//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLOutput;
import javax.swing.*;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.event.InternalFrameAdapter;

public class Roster extends JPanel {
    private static JList listaRoster;
    private JLabel labRoster;
    private JLabel bgRoster;

    public Roster() {
        //construct preComponents
        String[] listaRosterItems = {
                Zawodnik.listaZawodnikow.get(0).imie+ "   "+Zawodnik.listaZawodnikow.get(0).nazwisko+ "   "+Zawodnik.listaZawodnikow.get(0).numer+ "   "+Zawodnik.listaZawodnikow.get(0).dataUrodzenia,
                Zawodnik.listaZawodnikow.get(1).imie+ "   "+Zawodnik.listaZawodnikow.get(1).nazwisko+ "   "+Zawodnik.listaZawodnikow.get(1).numer+ "   "+Zawodnik.listaZawodnikow.get(1).dataUrodzenia,
                Zawodnik.listaZawodnikow.get(2).imie+ "   "+Zawodnik.listaZawodnikow.get(2).nazwisko+ "   "+Zawodnik.listaZawodnikow.get(2).numer+ "   "+Zawodnik.listaZawodnikow.get(2).dataUrodzenia,
                Zawodnik.listaZawodnikow.get(3).imie+ "   "+Zawodnik.listaZawodnikow.get(3).nazwisko+ "   "+Zawodnik.listaZawodnikow.get(3).numer+ "   "+Zawodnik.listaZawodnikow.get(3).dataUrodzenia,
                Zawodnik.listaZawodnikow.get(4).imie+ "   "+Zawodnik.listaZawodnikow.get(4).nazwisko+ "   "+Zawodnik.listaZawodnikow.get(4).numer+ "   "+Zawodnik.listaZawodnikow.get(4).dataUrodzenia,
                Zawodnik.listaZawodnikow.get(5).imie+ "   "+Zawodnik.listaZawodnikow.get(5).nazwisko+ "   "+Zawodnik.listaZawodnikow.get(5).numer+ "   "+Zawodnik.listaZawodnikow.get(5).dataUrodzenia,
                Zawodnik.listaZawodnikow.get(6).imie+ "   "+Zawodnik.listaZawodnikow.get(6).nazwisko+ "   "+Zawodnik.listaZawodnikow.get(6).numer+ "   "+Zawodnik.listaZawodnikow.get(6).dataUrodzenia,
                Zawodnik.listaZawodnikow.get(7).imie+ "   "+Zawodnik.listaZawodnikow.get(7).nazwisko+ "   "+Zawodnik.listaZawodnikow.get(7).numer+ "   "+Zawodnik.listaZawodnikow.get(7).dataUrodzenia,
                Zawodnik.listaZawodnikow.get(8).imie+ "   "+Zawodnik.listaZawodnikow.get(8).nazwisko+ "   "+Zawodnik.listaZawodnikow.get(8).numer+ "   "+Zawodnik.listaZawodnikow.get(8).dataUrodzenia,
                Zawodnik.listaZawodnikow.get(9).imie+ "   "+Zawodnik.listaZawodnikow.get(9).nazwisko+ "   "+Zawodnik.listaZawodnikow.get(9).numer+ "   "+Zawodnik.listaZawodnikow.get(9).dataUrodzenia,
                Zawodnik.listaZawodnikow.get(10).imie+ "   "+Zawodnik.listaZawodnikow.get(10).nazwisko+ "   "+Zawodnik.listaZawodnikow.get(10).numer+ "   "+Zawodnik.listaZawodnikow.get(10).dataUrodzenia,
                Zawodnik.listaZawodnikow.get(11).imie+ "   "+Zawodnik.listaZawodnikow.get(11).nazwisko+ "   "+Zawodnik.listaZawodnikow.get(11).numer+ "   "+Zawodnik.listaZawodnikow.get(11).dataUrodzenia,
                Zawodnik.listaZawodnikow.get(12).imie+ "   "+Zawodnik.listaZawodnikow.get(12).nazwisko+ "   "+Zawodnik.listaZawodnikow.get(12).numer+ "   "+Zawodnik.listaZawodnikow.get(12).dataUrodzenia,
                Zawodnik.listaZawodnikow.get(13).imie+ "   "+Zawodnik.listaZawodnikow.get(13).nazwisko+ "   "+Zawodnik.listaZawodnikow.get(13).numer+ "   "+Zawodnik.listaZawodnikow.get(13).dataUrodzenia,

        };


        //construct components
        listaRoster = new JList (listaRosterItems);
        labRoster = new JLabel ("ROSTER");
        bgRoster = new JLabel(new ImageIcon("img/bgRoster.png"));
        bgRoster.setBounds(0, 0, 358, 368);
        //adjust size and set layout
        setPreferredSize (new Dimension (358, 365));
        setLayout (null);


        //add components
        add (listaRoster);
        add (labRoster);
        add (bgRoster);

        //set component bounds (only needed by Absolute Positioning)
        listaRoster.setBounds (30, 76, 305, 270);
        labRoster.setBounds (145, 20, 365, 55);
        labRoster.setForeground(Color.WHITE);
        labRoster.setFont(new Font("Arial", Font.BOLD, 20));
    }
public static void zListy(){
    if(listaRoster.getSelectedIndex()==0){
        System.out.println("few");
    }
    }

    public static void main () {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Roster());
        frame.pack();
        frame.setVisible (true);

    }
}
