//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;



public class ZawodnikUklad extends JPanel {

    private JLabel bground;
    private JLabel naziwso;
    private JLabel zdjecie;
    private JLabel wynik1;
    private JLabel ppg2;
    private JLabel wynik3;
    private JLabel wynik4;
    private JLabel wynik5;
    private JLabel imie;
    private JLabel ppg_4;
    private JLabel apg5;
    private JLabel logo1;
    private JLabel fg1;
    private JLabel ppg1;
    private JLabel ppg_1;
    private JLabel apg1;
    private JLabel apg_1;
    private JLabel rpgS;
    private JLabel rpg1;
    private JLabel fgS;
    private JLabel ppg3;
    private JLabel wynik2;
    private JLabel logo2;
    private JLabel logo3;
    private JLabel logo5;
    private JLabel logo4;
    private JLabel ppg_2;
    private JLabel fg2;
    private JLabel ppg_3;
    private JLabel ppg4;
    private JLabel ppg5;
    private JLabel ppg_5;
    private JLabel apg3;
    private JLabel apg2;
    private JLabel apg_2;
    private JLabel rpgSS;
    private JLabel rpg2;
    private JLabel fgSS;
    private JLabel rpgSSSS;
    private JLabel fgSSSSS;
    private JLabel apg_4;
    private JLabel rpg4;
    private JLabel fg5;
    private JLabel fgSSS;
    private JLabel apg_3;
    private JLabel fg4;
    private JLabel fg3;
    private JLabel rpgSSS;
    private JLabel fgSSSS;
    private JLabel apg4;
    private JLabel rpg3;
    private JLabel rpg5;
    private JLabel rpgSSSSS;
    private JLabel apg_5;
    private JButton butt_pop;
    private JButton but_nas;
    private JLabel ppg;
    private JLabel ppg_n;
    private JLabel apg;
    private JLabel apg_n;
    private JLabel rpg;
    private JLabel rpg_n;
    private JLabel label;
    private JLabel numer;
    private JLabel fg;
    private JLabel fg_n;
    private JButton but_tab;
    private JButton but_mecz;
    private JButton but_ros;
    private JButton but_sta;
    private JButton but_apl;
    int i = 0;

    public ZawodnikUklad() {

        //construct components

        imie = new JLabel(Zawodnik.listaZawodnikow.get(i).imie);
        zdjecie = new JLabel(new ImageIcon(Zawodnik.listaZawodnikow.get(i).zdjecie));
        naziwso = new JLabel(Zawodnik.listaZawodnikow.get(i).nazwisko);
        wynik1 = new JLabel(String.valueOf(Mecz.listaMeczy.get(Mecz.listaMeczy.size() - 1).philaPoints) + " : " + String.valueOf(Mecz.listaMeczy.get(Mecz.listaMeczy.size() - 1).enemyPoints));
        ppg2 = new JLabel("PTS");
        wynik3 = new JLabel(String.valueOf(Mecz.listaMeczy.get(Mecz.listaMeczy.size() - 3).philaPoints) + " : " + String.valueOf(Mecz.listaMeczy.get(Mecz.listaMeczy.size() - 3).enemyPoints));
        wynik4 = new JLabel(String.valueOf(Mecz.listaMeczy.get(Mecz.listaMeczy.size() - 4).philaPoints) + " : " + String.valueOf(Mecz.listaMeczy.get(Mecz.listaMeczy.size() - 4).enemyPoints));
        wynik5 = new JLabel(String.valueOf(Mecz.listaMeczy.get(Mecz.listaMeczy.size() - 5).philaPoints) + " : " + String.valueOf(Mecz.listaMeczy.get(Mecz.listaMeczy.size() - 5).enemyPoints));
        ppg_4 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-4).pts));
        apg5 = new JLabel("AST");
        logo1 = new JLabel(new ImageIcon(Mecz.listaMeczy.get(Mecz.listaMeczy.size() - 1).image));
        fg1 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-1).fg));
        ppg1 = new JLabel("PTS");
        ppg_1 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-1).pts));
        apg1 = new JLabel("AST");
        apg_1 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-1).ast));
        rpgS = new JLabel("REB");
        rpg1 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-1).reb));
        fgS = new JLabel("FG%");
        ppg3 = new JLabel("PTS");
        wynik2 = new JLabel(String.valueOf(Mecz.listaMeczy.get(Mecz.listaMeczy.size() - 2).philaPoints) + " : " + String.valueOf(Mecz.listaMeczy.get(Mecz.listaMeczy.size() - 2).enemyPoints));
        logo2 = new JLabel(new ImageIcon(Mecz.listaMeczy.get(Mecz.listaMeczy.size() - 2).image));
        logo3 = new JLabel(new ImageIcon(Mecz.listaMeczy.get(Mecz.listaMeczy.size() - 3).image));
        logo5 = new JLabel(new ImageIcon(Mecz.listaMeczy.get(Mecz.listaMeczy.size() - 5).image));
        logo4 = new JLabel(new ImageIcon(Mecz.listaMeczy.get(Mecz.listaMeczy.size() - 4).image));
        ppg_2 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-2).pts));
        fg2 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-2).fg));
        ppg_3 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-3).pts));
        ppg4 = new JLabel("PTS");
        ppg5 = new JLabel("PTS");
        ppg_5 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-5).pts));
        apg3 = new JLabel("AST");
        apg2 = new JLabel("AST");
        apg_2 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-2).ast));
        rpgSS = new JLabel("REB");
        rpg2 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-2).reb));
        fgSS = new JLabel("FG%");
        rpgSSSS = new JLabel("REB");
        fgSSSSS = new JLabel("FG%");
        apg_4 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-4).ast));
        rpg4 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-4).reb));
        fg5 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-5).fg));
        fgSSS = new JLabel("FG%");
        apg_3 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-3).ast));
        fg4 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-4).fg));
        fg3 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-3).fg));
        rpgSSS = new JLabel("REB");
        fgSSSS = new JLabel("FG%");
        apg4 = new JLabel("AST");
        rpg3 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-3).reb));
        rpg5 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-5).reb));
        rpgSSSSS = new JLabel("REB");
        apg_5 = new JLabel(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-5).ast));
        butt_pop = new JButton("Poprzedni");
        but_nas = new JButton("Następny");
        ppg = new JLabel("PPG");
        ppg_n = new JLabel(String.valueOf(StatystykiZawodnika.statystykiPTS(0)));
        apg = new JLabel("APG");
        apg_n = new JLabel(String.valueOf(StatystykiZawodnika.statystykiAST(0)));
        rpg = new JLabel("RPG");
        rpg_n = new JLabel("6.8");
        label = new JLabel("Ostatnie 5 meczy");
        numer = new JLabel("#" + String.valueOf(Zawodnik.listaZawodnikow.get(0).numer));
        fg = new JLabel("FG%");
        fg_n = new JLabel("80%");
        but_tab = new JButton("Tabela");
        but_mecz = new JButton("Mecze");
        but_ros = new JButton("Roster");
        but_sta = new JButton("Statystyki");
        but_apl = new JButton("O aplikacji");

        bground = new JLabel(new ImageIcon("img/bg.png"));


        //adjust size and set layout
        setPreferredSize(new Dimension(608, 839));
        setLayout(null);

        //add components

        add(naziwso);
        add(zdjecie);
        add(wynik1);
        add(ppg2);
        add(wynik3);
        add(wynik4);
        add(wynik5);
        add(imie);
        add(ppg_4);
        add(apg5);
        add(logo1);
        add(fg1);
        add(ppg1);
        add(ppg_1);
        add(apg1);
        add(apg_1);
        add(rpgS);
        add(rpg1);
        add(fgS);
        add(ppg3);
        add(wynik2);
        add(logo2);
        add(logo3);
        add(logo5);
        add(logo4);
        add(ppg_2);
        add(fg2);
        add(ppg_3);
        add(ppg4);
        add(ppg5);
        add(ppg_5);
        add(apg3);
        add(apg2);
        add(apg_2);
        add(rpgSS);
        add(rpg2);
        add(fgSS);
        add(rpgSSSS);
        add(fgSSSSS);
        add(apg_4);
        add(rpg4);
        add(fg5);
        add(fgSSS);
        add(apg_3);
        add(fg4);
        add(fg3);
        add(rpgSSS);
        add(fgSSSS);
        add(apg4);
        add(rpg3);
        add(rpg5);
        add(rpgSSSSS);
        add(apg_5);
        add(butt_pop);
        add(but_nas);
        add(ppg);
        add(ppg_n);
        add(apg);
        add(apg_n);
        add(rpg);
        add(rpg_n);
        add(label);
        add(numer);
        add(fg);
        add(fg_n);
        add(but_tab);
        add(but_mecz);
        add(but_ros);
        add(but_sta);
        add(but_apl);
        add(bground);


        //set component bounds (only needed by Absolute Positioning)
        bground.setBounds(0, 0, 610, 840);
        naziwso.setBounds(30, 185, 210, 60);
        zdjecie.setBounds(345, 30, 200, 215);
        wynik1.setBounds(30, 405, 80, 50);
        ppg2.setBounds(225, 455, 40, 50);
        wynik3.setBounds(30, 505, 80, 50);
        wynik4.setBounds(30, 555, 80, 50);
        wynik5.setBounds(30, 605, 80, 50);
        imie.setBounds(35, 106, 300, 90);
        ppg_4.setBounds(265, 555, 40, 50);
        apg5.setBounds(305, 605, 40, 50);
        logo1.setBounds(110, 405, 60, 50);
        fg1.setBounds(505, 405, 40, 50);
        ppg1.setBounds(225, 405, 40, 50);
        ppg_1.setBounds(265, 405, 40, 50);
        apg1.setBounds(305, 405, 40, 50);
        apg_1.setBounds(345, 405, 40, 50);
        rpgS.setBounds(385, 405, 40, 50);
        rpg1.setBounds(425, 405, 40, 50);
        fgS.setBounds(465, 405, 40, 50);
        ppg3.setBounds(225, 505, 40, 50);
        wynik2.setBounds(30, 455, 80, 50);
        logo2.setBounds(110, 455, 60, 50);
        logo3.setBounds(110, 505, 60, 50);
        logo5.setBounds(110, 605, 60, 50);
        logo4.setBounds(110, 555, 60, 50);
        ppg_2.setBounds(265, 455, 40, 50);
        fg2.setBounds(505, 455, 40, 50);
        ppg_3.setBounds(265, 505, 40, 50);
        ppg4.setBounds(225, 555, 40, 50);
        ppg5.setBounds(225, 605, 40, 50);
        ppg_5.setBounds(265, 605, 40, 50);
        apg3.setBounds(305, 505, 40, 50);
        apg2.setBounds(305, 455, 40, 50);
        apg_2.setBounds(345, 455, 40, 50);
        rpgSS.setBounds(385, 455, 40, 50);
        rpg2.setBounds(425, 455, 40, 50);
        fgSS.setBounds(465, 455, 40, 50);
        rpgSSSS.setBounds(385, 555, 40, 50);
        fgSSSSS.setBounds(465, 605, 40, 50);
        apg_4.setBounds(345, 555, 40, 50);
        rpg4.setBounds(425, 555, 40, 50);
        fg5.setBounds(505, 605, 40, 50);
        fgSSS.setBounds(465, 505, 40, 50);
        apg_3.setBounds(345, 505, 40, 50);
        fg4.setBounds(505, 555, 40, 50);
        fg3.setBounds(505, 505, 40, 50);
        rpgSSS.setBounds(385, 505, 40, 50);
        fgSSSS.setBounds(465, 555, 40, 50);
        apg4.setBounds(305, 555, 40, 50);
        rpg3.setBounds(425, 505, 40, 50);
        rpg5.setBounds(425, 605, 40, 50);
        rpgSSSSS.setBounds(385, 605, 40, 50);
        apg_5.setBounds(345, 605, 40, 50);
        butt_pop.setBounds(185, 725, 100, 25);
        but_nas.setBounds(320, 725, 100, 25);
        ppg.setBounds(50, 255, 60, 50);
        ppg_n.setBounds(110, 255, 60, 50);
        apg.setBounds(170, 255, 60, 50);
        apg_n.setBounds(230, 255, 60, 50);
        rpg.setBounds(290, 255, 60, 50);
        rpg_n.setBounds(350, 255, 60, 50);
        label.setBounds(30, 350, 260, 50);
        numer.setBounds(240, 185, 85, 60);
        fg.setBounds(410, 255, 60, 50);
        fg_n.setBounds(470, 255, 60, 50);
        but_tab.setBounds(250, 780, 100, 50);
        but_mecz.setBounds(150, 780, 100, 50);
        but_ros.setBounds(50, 780, 100, 50);
        but_sta.setBounds(350, 780, 100, 50);
        but_apl.setBounds(450, 780, 100, 50);

        //Ustawienie koloru wyników meczy
        if (Mecz.ustawKolor(1) == 1) wynik1.setForeground(Color.RED);
        if (Mecz.ustawKolor(1) == 2) wynik1.setForeground(Color.GREEN);
        if (Mecz.ustawKolor(2) == 1) wynik2.setForeground(Color.RED);
        if (Mecz.ustawKolor(2) == 2) wynik2.setForeground(Color.GREEN);
        if (Mecz.ustawKolor(3) == 1) wynik3.setForeground(Color.RED);
        if (Mecz.ustawKolor(3) == 2) wynik3.setForeground(Color.GREEN);
        if (Mecz.ustawKolor(4) == 1) wynik4.setForeground(Color.RED);
        if (Mecz.ustawKolor(4) == 2) wynik4.setForeground(Color.GREEN);
        if (Mecz.ustawKolor(5) == 1) wynik5.setForeground(Color.RED);
        if (Mecz.ustawKolor(5) == 2) wynik5.setForeground(Color.GREEN);


        naziwso.setForeground(Color.WHITE);
        naziwso.setFont(new Font("Arial", Font.BOLD, 45));
        imie.setForeground(Color.WHITE);
        imie.setFont(new Font("Arial", Font.BOLD, 45));
        numer.setForeground(Color.red);
        numer.setFont(new Font("Arial", Font.BOLD, 45));
        label.setForeground(Color.WHITE);
        label.setFont(new Font("Arial", Font.BOLD, 30));

        wynik1.setFont(new Font("Arial", Font.BOLD, 16));
        wynik3.setFont(new Font("Arial", Font.BOLD, 16));
        wynik2.setFont(new Font("Arial", Font.BOLD, 16));
        wynik4.setFont(new Font("Arial", Font.BOLD, 16));
        wynik5.setFont(new Font("Arial", Font.BOLD, 16));

        ppg_1.setForeground(Color.WHITE);
        ppg_1.setFont(new Font("Arial", Font.BOLD, 16));
        ppg_2.setForeground(Color.WHITE);
        ppg_2.setFont(new Font("Arial", Font.BOLD, 16));
        ppg_3.setForeground(Color.WHITE);
        ppg_3.setFont(new Font("Arial", Font.BOLD, 16));
        ppg_4.setForeground(Color.WHITE);
        ppg_4.setFont(new Font("Arial", Font.BOLD, 16));
        ppg_5.setForeground(Color.WHITE);
        ppg_5.setFont(new Font("Arial", Font.BOLD, 16));

        ppg1.setForeground(Color.GRAY);
        ppg1.setFont(new Font("Arial", Font.BOLD, 16));
        ppg2.setForeground(Color.GRAY);
        ppg2.setFont(new Font("Arial", Font.BOLD, 16));
        ppg3.setForeground(Color.GRAY);
        ppg3.setFont(new Font("Arial", Font.BOLD, 16));
        ppg4.setForeground(Color.GRAY);
        ppg4.setFont(new Font("Arial", Font.BOLD, 16));
        ppg5.setForeground(Color.GRAY);
        ppg5.setFont(new Font("Arial", Font.BOLD, 16));

        apg_1.setForeground(Color.WHITE);
        apg_1.setFont(new Font("Arial", Font.BOLD, 16));
        apg_2.setForeground(Color.WHITE);
        apg_2.setFont(new Font("Arial", Font.BOLD, 16));
        apg_3.setForeground(Color.WHITE);
        apg_3.setFont(new Font("Arial", Font.BOLD, 16));
        apg_4.setForeground(Color.WHITE);
        apg_4.setFont(new Font("Arial", Font.BOLD, 16));
        apg_5.setForeground(Color.WHITE);
        apg_5.setFont(new Font("Arial", Font.BOLD, 16));

        fg1.setForeground(Color.WHITE);
        fg1.setFont(new Font("Arial", Font.BOLD, 16));
        fg2.setForeground(Color.WHITE);
        fg2.setFont(new Font("Arial", Font.BOLD, 16));
        fg4.setForeground(Color.WHITE);
        fg4.setFont(new Font("Arial", Font.BOLD, 16));
        fg3.setForeground(Color.WHITE);
        fg3.setFont(new Font("Arial", Font.BOLD, 16));
        fg5.setForeground(Color.WHITE);
        fg5.setFont(new Font("Arial", Font.BOLD, 16));

        rpg1.setForeground(Color.WHITE);
        rpg1.setFont(new Font("Arial", Font.BOLD, 16));
        rpg2.setForeground(Color.WHITE);
        rpg2.setFont(new Font("Arial", Font.BOLD, 16));
        rpg3.setForeground(Color.WHITE);
        rpg3.setFont(new Font("Arial", Font.BOLD, 16));
        rpg4.setForeground(Color.WHITE);
        rpg4.setFont(new Font("Arial", Font.BOLD, 16));
        rpg5.setForeground(Color.WHITE);
        rpg5.setFont(new Font("Arial", Font.BOLD, 16));

        ppg_n.setForeground(Color.WHITE);
        ppg_n.setFont(new Font("Arial", Font.BOLD, 25));
        apg_n.setForeground(Color.WHITE);
        apg_n.setFont(new Font("Arial", Font.BOLD, 25));
        rpg_n.setForeground(Color.WHITE);
        rpg_n.setFont(new Font("Arial", Font.BOLD, 25));
        fg_n.setForeground(Color.WHITE);
        fg_n.setFont(new Font("Arial", Font.BOLD, 25));
        apg.setForeground(Color.gray);
        apg.setFont(new Font("Arial", Font.BOLD, 25));
        rpg.setForeground(Color.gray);
        rpg.setFont(new Font("Arial", Font.BOLD, 25));
        fg.setForeground(Color.gray);
        fg.setFont(new Font("Arial", Font.BOLD, 25));
        ppg.setForeground(Color.gray);
        ppg.setFont(new Font("Arial", Font.BOLD, 25));

        apg1.setForeground(Color.GRAY);
        apg1.setFont(new Font("Arial", Font.BOLD, 16));
        apg2.setForeground(Color.GRAY);
        apg2.setFont(new Font("Arial", Font.BOLD, 16));
        apg3.setForeground(Color.GRAY);
        apg3.setFont(new Font("Arial", Font.BOLD, 16));
        apg4.setForeground(Color.GRAY);
        apg4.setFont(new Font("Arial", Font.BOLD, 16));
        apg5.setForeground(Color.GRAY);
        apg5.setFont(new Font("Arial", Font.BOLD, 16));

        rpgS.setForeground(Color.GRAY);
        rpgS.setFont(new Font("Arial", Font.BOLD, 16));
        rpgSSS.setForeground(Color.GRAY);
        rpgSSS.setFont(new Font("Arial", Font.BOLD, 16));
        rpgSSSS.setForeground(Color.GRAY);
        rpgSSSS.setFont(new Font("Arial", Font.BOLD, 16));
        rpgSSSSS.setForeground(Color.GRAY);
        rpgSSSSS.setFont(new Font("Arial", Font.BOLD, 16));
        fgS.setForeground(Color.GRAY);
        fgS.setFont(new Font("Arial", Font.BOLD, 16));
        fgSS.setForeground(Color.GRAY);
        fgSS.setFont(new Font("Arial", Font.BOLD, 16));
        fgSSS.setForeground(Color.GRAY);
        fgSSS.setFont(new Font("Arial", Font.BOLD, 16));
        fgSSSS.setForeground(Color.GRAY);
        fgSSSS.setFont(new Font("Arial", Font.BOLD, 16));
        fgSSSSS.setForeground(Color.GRAY);
        fgSSSSS.setFont(new Font("Arial", Font.BOLD, 16));
        rpgSS.setForeground(Color.GRAY);
        rpgSS.setFont(new Font("Arial", Font.BOLD, 16));
        //Przyciski
        but_ros.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                JFrame frame = new JFrame ("Phila 76");
                frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
                frame.getContentPane().add (new Roster());
                frame.pack();
                frame.setVisible (true);

            }
        });
        butt_pop.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (i > 0)
                {i--;
                zdjecie.setIcon(new ImageIcon(Zawodnik.listaZawodnikow.get(i).zdjecie));
                naziwso.setText(Zawodnik.listaZawodnikow.get(i).nazwisko);
                imie.setText(Zawodnik.listaZawodnikow.get(i).imie);
                numer.setText("#"+Zawodnik.listaZawodnikow.get(i).numer);
                ppg_n.setText(String.valueOf(StatystykiZawodnika.statystykiPTS(i)));
                apg_n.setText(String.valueOf(StatystykiZawodnika.statystykiAST(i)));
                    rpg_n.setText(String.valueOf(StatystykiZawodnika.statystykiREB(i)));
                    fg_n.setText(String.valueOf(StatystykiZawodnika.statystykiFG(i)));
                }
                if (i==0){
                    ppg_1.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-1).pts));
                    ppg_2.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-2).pts));
                    ppg_3.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-3).pts));
                    ppg_4.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-4).pts));
                    ppg_5.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-5).pts));

                    apg_1.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-1).ast));
                    apg_2.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-2).ast));
                    apg_3.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-3).ast));
                    apg_4.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-4).ast));
                    apg_5.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-5).ast));

                    rpg1.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-1).reb));
                    rpg2.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-2).reb));
                    rpg3.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-3).reb));
                    rpg4.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-4).reb));
                    rpg5.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-5).reb));

                    fg1.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-1).fg));
                    fg2.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-2).fg));
                    fg3.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-3).fg));
                    fg4.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-4).fg));
                    fg5.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-5).fg));
                }
                if (i==1){
                   ppg_1.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-1).pts));
                   ppg_2.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-2).pts));
                   ppg_3.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-3).pts));
                   ppg_4.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-4).pts));
                   ppg_5.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-5).pts));

                   apg_1.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-1).ast));
                   apg_2.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-2).ast));
                   apg_3.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-3).ast));
                   apg_4.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-4).ast));
                   apg_5.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-5).ast));

                   rpg1.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-1).reb));
                   rpg2.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-2).reb));
                   rpg3.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-3).reb));
                   rpg4.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-4).reb));
                   rpg5.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-5).reb));

                   fg1.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-1).fg));
                   fg2.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-2).fg));
                   fg3.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-3).fg));
                   fg4.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-4).fg));
                   fg5.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-5).fg));
                }
                if (i==2){
                    ppg_1.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-1).pts));
                    ppg_2.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-2).pts));
                    ppg_3.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-3).pts));
                    ppg_4.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-4).pts));
                    ppg_5.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-5).pts));

                    apg_1.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-1).ast));
                    apg_2.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-2).ast));
                    apg_3.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-3).ast));
                    apg_4.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-4).ast));
                    apg_5.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-5).ast));

                    rpg1.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-1).reb));
                    rpg2.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-2).reb));
                    rpg3.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-3).reb));
                    rpg4.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-4).reb));
                    rpg5.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-5).reb));

                    fg1.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-1).fg));
                    fg2.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-2).fg));
                    fg3.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-3).fg));
                    fg4.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-4).fg));
                    fg5.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-5).fg));
                }
            }
        });
        but_nas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (i < Zawodnik.listaZawodnikow.size()-1)
                {i++;
                zdjecie.setIcon(new ImageIcon(Zawodnik.listaZawodnikow.get(i).zdjecie));
                naziwso.setText(Zawodnik.listaZawodnikow.get(i).nazwisko);
                imie.setText(Zawodnik.listaZawodnikow.get(i).imie);
                numer.setText("#"+Zawodnik.listaZawodnikow.get(i).numer);}
                ppg_n.setText(String.valueOf(StatystykiZawodnika.statystykiPTS(i)));
                apg_n.setText(String.valueOf(StatystykiZawodnika.statystykiAST(i)));
                rpg_n.setText(String.valueOf(StatystykiZawodnika.statystykiREB(i)));
                fg_n.setText(String.valueOf(StatystykiZawodnika.statystykiFG(i)));
                System.out.println(i);
                if (i==0){
                    ppg_1.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-1).pts));
                    ppg_2.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-2).pts));
                    ppg_3.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-3).pts));
                    ppg_4.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-4).pts));
                    ppg_5.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-5).pts));

                    apg_1.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-1).ast));
                    apg_2.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-2).ast));
                    apg_3.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-3).ast));
                    apg_4.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-4).ast));
                    apg_5.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-5).ast));

                    rpg1.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-1).reb));
                    rpg2.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-2).reb));
                    rpg3.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-3).reb));
                    rpg4.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-4).reb));
                    rpg5.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-5).reb));

                    fg1.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-1).fg));
                    fg2.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-2).fg));
                    fg3.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-3).fg));
                    fg4.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-4).fg));
                    fg5.setText(String.valueOf(StatystykiZawodnika.listaMaxey.get(StatystykiZawodnika.listaMaxey.size()-5).fg));
                }
                if (i==1){
                    ppg_1.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-1).pts));
                    ppg_2.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-2).pts));
                    ppg_3.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-3).pts));
                    ppg_4.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-4).pts));
                    ppg_5.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-5).pts));

                    apg_1.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-1).ast));
                    apg_2.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-2).ast));
                    apg_3.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-3).ast));
                    apg_4.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-4).ast));
                    apg_5.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-5).ast));

                    rpg1.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-1).reb));
                    rpg2.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-2).reb));
                    rpg3.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-3).reb));
                    rpg4.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-4).reb));
                    rpg5.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-5).reb));

                    fg1.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-1).fg));
                    fg2.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-2).fg));
                    fg3.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-3).fg));
                    fg4.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-4).fg));
                    fg5.setText(String.valueOf(StatystykiZawodnika.listaEmbiid.get(StatystykiZawodnika.listaEmbiid.size()-5).fg));
                }
                if (i==2){
                    ppg_1.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-1).pts));
                    ppg_2.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-2).pts));
                    ppg_3.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-3).pts));
                    ppg_4.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-4).pts));
                    ppg_5.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-5).pts));

                    apg_1.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-1).ast));
                    apg_2.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-2).ast));
                    apg_3.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-3).ast));
                    apg_4.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-4).ast));
                    apg_5.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-5).ast));

                    rpg1.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-1).reb));
                    rpg2.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-2).reb));
                    rpg3.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-3).reb));
                    rpg4.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-4).reb));
                    rpg5.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-5).reb));

                    fg1.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-1).fg));
                    fg2.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-2).fg));
                    fg3.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-3).fg));
                    fg4.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-4).fg));
                    fg5.setText(String.valueOf(StatystykiZawodnika.listaMelton.get(StatystykiZawodnika.listaMelton.size()-5).fg));
                }
            }
        });

    }

    public static void main() {
        JFrame framee = new JFrame("Phila 76sers");
        framee.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ImageIcon icon = new ImageIcon("img/logo.png");
        framee.getContentPane().add(new ZawodnikUklad());
        framee.pack();
        framee.setLocationRelativeTo(null);
        framee.setVisible(true);
        framee.setResizable(false);
    }
}